_wandb:
    value:
        cli_version: 0.23.1
        e:
            wdmxvi29xmxzhclzasrt76srf0jyqdcd:
                args:
                    - --app
                    - .
                    - --num-supernodes
                    - "1000"
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "142100365312"
                        used: "110505263104"
                email: lucasmascalmeida@gmail.com
                executable: /home/mascalmeida/miniconda3/envs/flower/bin/python3.11
                git:
                    commit: cbece31637531b6807474544597ac7f538d8db32
                    remote: https://github.com/mascalmeida/flower-tutorial.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-5d869432-961e-3e50-9f29-7f75ae2d3507
                host: mascalmeida-pc
                memory:
                    total: "8182841344"
                os: Linux-5.15.0-164-generic-x86_64-with-glibc2.35
                program: /home/mascalmeida/miniconda3/envs/flower/bin/flower-simulation
                python: CPython 3.11.14
                root: /home/mascalmeida/Documents/codes/flower-tutorial
                startedAt: "2025-12-14T22:11:02.032526Z"
                writerId: wdmxvi29xmxzhclzasrt76srf0jyqdcd
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 30
                - 41
                - 49
                - 51
            "2":
                - 1
                - 30
                - 41
                - 49
                - 51
            "3":
                - 13
                - 61
            "4": 3.11.14
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
