_wandb:
    value:
        cli_version: 0.23.1
        e:
            l9jfcshjenvezdds3sjwq9djb7676jrx:
                args:
                    - --app
                    - .
                    - --num-supernodes
                    - "1000"
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "508908531712"
                        used: "145928396800"
                email: lucasmascalmeida@gmail.com
                executable: C:\Users\LucasMascarenhas\miniconda3\envs\phd\python.exe
                git:
                    commit: f518fbd31605dab3fdf189f44ebd0789ab8b0eb9
                    remote: https://github.com/mascalmeida/flower-tutorial.git
                host: SHAPE-000342
                memory:
                    total: "34029125632"
                os: Windows-10-10.0.26200-SP0
                program: -m __main__
                python: CPython 3.10.19
                root: C:\Users\LucasMascarenhas\OneDrive - Shape Digital\Pessoal\Doutorado\Codes\flower-tutorial
                startedAt: "2025-12-15T11:47:14.398837Z"
                writerId: l9jfcshjenvezdds3sjwq9djb7676jrx
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 30
                - 41
                - 49
                - 51
            "2":
                - 1
                - 30
                - 41
                - 49
                - 51
            "3":
                - 13
                - 61
            "4": 3.10.19
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
